### ISSUE TITLE
A year later, are you still using PHPSpec, a year later, did you really use PHPSpec?

### ISSUE THREAD

**Issue by zanematthew** [kmcculloch/block_example_phpspec#1]
First, thanks for taking the time to contribute, and present.

I've always been interested in PHPSpec, but have yet to see it used in an agency environment.

I have two questions;

1. Are you still using PHPSpec?

2. Did you _actually_ use PHPSpec as it is intended? You are intended to _describe_ the functionality of your objects, create your test/spec first, and let PHPSpec generate your code, then you create the functionality. 

>BDD is a technique used at story level and spec level. phpspec is a tool for use at the spec level or SpecBDD. The technique is to first use a tool like phpspec to describe the behaviour of an object you are about to write. Next you write just enough code to meet that specification and finally you refactor this code.

As the docs contain; `$ bin/phpspec desc Acme/Calculator`, which will generate your Spec, from there you can have PHPSpec generate your class.

With that being said, explain how you configured PHPSpec to create Drupal objects?

`$ bin/phpspec desc Drupal\SomeClass`

**Comment by kmcculloch** [comment]
@zanematthew Yes I still use PHPSpec for Drupal projects, and I often (although not always) will _actually_ generate the spec test object before filling in the functionality. It depends a bit on what I'm trying to make. :)

For Drupal 7 projects, I put my `spec` and `src` folders right next to each other in the module directory like so:

```
docroot/sites/all/modules/custom/my_module
--spec/
--src/
--my_module.info
--my_module.module
```

Then I have to tell PHPSpec where to find this code. First, I add an entry for each module in a `phpspec.yml` file at the top of the repo:

```
suites:
  my_module:
    namespace: Drupal\my_module
    psr4_prefix: Drupal\my_module
    src_path: docroot/sites/all/modules/custom/my_module/src
    spec_path: docroot/sites/all/modules/custom/my_module
```

Then I add an `autoload-dev` key to my `composer.json`, and do a `composer dump-autoload` to pick it up, so that the same Composer context that PHPSpec runs in can actually load and run my module code:

```
    "autoload-dev": {
        "psr-4": {
            "Drupal\\my_module\\": "docroot/sites/all/modules/custom/my_module/src/"
        }
    }
```

Then I can just run `phpspec run` from the repo root and it will find and run tests. Likewise `phpspec desc Drupal/my_module/SomeClass` will put `SomeClass.php` in the `src` directory inside my module where it belongs.
